import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return {
      small: {
        rows: [
          {
            'browser' : 'Chrome',
            'november': '48.15%',
            'december': '46.22%',
            'change'  : '-1.93%',
            'relative': '-4.00%',
            '_private': 'foo'
          },
          {
            'browser' : 'Firefox',
            'november': '16.76%',
            'december': '16.34%',
            'change'  : '-0.42%',
            'relative': '-2.50%',
            '_private': 'bar'
          },
          {
            'browser' : 'Safari',
            'november': '4.45%',
            'december': '4.24%',
            'change'  : '-0.21%',
            'relative': '-4.70%',
            '_private': 'foo'
          }
        ]
      },
      big: {
        rows: [ {
          'last_name' : 'Billups',
          'first_name' : 'Chauncey',
          'display_name' : 'Chauncey Billups',
          'birthdate' : '1976-09-25',
          'age' : 37,
          'birthplace' : 'Denver, Colorado, USA',
          'height_in' : 75,
          'height_cm' : 190.5,
          'height_m' : 1.9,
          'height_formatted' : '6\'3\'',
          'weight_lb' : 202,
          'weight_kg' : 91.8,
          'position' : 'PG',
          'uniform_number' : 1
        }, {
          'last_name' : 'Bynum',
          'first_name' : 'William',
          'display_name' : 'Will Bynum',
          'birthdate' : '1983-01-04',
          'age' : 30,
          'birthplace' : 'Chicago, Illinois, USA',
          'height_in' : 72,
          'height_cm' : 182.9,
          'height_m' : 1.8,
          'height_formatted' : '6\'0\'',
          'weight_lb' : 185,
          'weight_kg' : 84.1,
          'position' : 'PG',
          'uniform_number' : 12
        }, {
          'last_name' : 'Caldwell-Pope',
          'first_name' : 'Kentavious',
          'display_name' : 'Kentavious Caldwell-Pope',
          'birthdate' : '1993-02-18',
          'age' : 20,
          'birthplace' : 'Thomaston, Georgia, USA',
          'height_in' : 78,
          'height_cm' : 198.1,
          'height_m' : 2.0,
          'height_formatted' : '6\'6\'',
          'weight_lb' : 204,
          'weight_kg' : 92.7,
          'position' : 'SG',
          'uniform_number' : 5
        }, {
          'last_name' : 'Datome',
          'first_name' : 'Luigi',
          'display_name' : 'Luigi Datome',
          'birthdate' : '1987-11-27',
          'age' : 25,
          'birthplace' : 'Montebelluna, Italy',
          'height_in' : 80,
          'height_cm' : 203.2,
          'height_m' : 2.0,
          'height_formatted' : '6\'8\'',
          'weight_lb' : 198,
          'weight_kg' : 90.0,
          'position' : 'SG',
          'uniform_number' : 13
        }, {
          'last_name' : 'Drummond',
          'first_name' : 'Andre',
          'display_name' : 'Andre Drummond',
          'birthdate' : '1993-08-10',
          'age' : 20,
          'birthplace' : 'Middletown, Connecticut, USA',
          'height_in' : 83,
          'height_cm' : 210.8,
          'height_m' : 2.1,
          'height_formatted' : '6\'11\'',
          'weight_lb' : 275,
          'weight_kg' : 125.0,
          'position' : 'PF',
          'uniform_number' : 0
        }, {
          'last_name' : 'Harrellson',
          'first_name' : 'Josh',
          'display_name' : 'Josh Harrellson',
          'birthdate' : '1989-02-12',
          'age' : 24,
          'birthplace' : 'Saint Charles, Missouri, USA',
          'height_in' : 82,
          'height_cm' : 208.3,
          'height_m' : 2.1,
          'height_formatted' : '6\'10\'',
          'weight_lb' : 275,
          'weight_kg' : 125.0,
          'position' : 'C',
          'uniform_number' : 55
        }, {
          'last_name' : 'Jennings',
          'first_name' : 'Brandon',
          'display_name' : 'Brandon Jennings',
          'birthdate' : '1989-09-23',
          'age' : 24,
          'birthplace' : 'Los Angeles, California, USA',
          'height_in' : 73,
          'height_cm' : 185.4,
          'height_m' : 1.9,
          'height_formatted' : '6\'1\'',
          'weight_lb' : 170,
          'weight_kg' : 77.3,
          'position' : 'PG',
          'uniform_number' : 7
        }, {
          'last_name' : 'Jerebko',
          'first_name' : 'Jonas',
          'display_name' : 'Jonas Jerebko',
          'birthdate' : '1987-03-02',
          'age' : 26,
          'birthplace' : 'Kinna, Sweden',
          'height_in' : 81,
          'height_cm' : 205.7,
          'height_m' : 2.1,
          'height_formatted' : '6\'9\'',
          'weight_lb' : 220,
          'weight_kg' : 100.0,
          'position' : 'SF',
          'uniform_number' : 33
        }, {
          'last_name' : 'Mitchell',
          'first_name' : 'Tony',
          'display_name' : 'Tony Mitchell',
          'birthdate' : '1992-04-07',
          'age' : 21,
          'birthplace' : 'Milwaukee, Wisconsin, USA',
          'height_in' : 81,
          'height_cm' : 205.7,
          'height_m' : 2.1,
          'height_formatted' : '6\'9\'',
          'weight_lb' : 236,
          'weight_kg' : 107.3,
          'position' : 'SF',
          'uniform_number' : 9
        }, {
          'last_name' : 'Monroe',
          'first_name' : 'Greg',
          'display_name' : 'Greg Monroe',
          'birthdate' : '1990-06-04',
          'age' : 23,
          'birthplace' : 'Harvey, Louisiana, USA',
          'height_in' : 83,
          'height_cm' : 210.8,
          'height_m' : 2.1,
          'height_formatted' : '6\'11\'',
          'weight_lb' : 247,
          'weight_kg' : 112.3,
          'position' : 'C',
          'uniform_number' : 10
        }, {
          'last_name' : 'Singler',
          'first_name' : 'Kyle',
          'display_name' : 'Kyle Singler',
          'birthdate' : '1988-05-04',
          'age' : 25,
          'birthplace' : 'Medford, Oregon, USA',
          'height_in' : 80,
          'height_cm' : 203.2,
          'height_m' : 2.0,
          'height_formatted' : '6\'8\'',
          'weight_lb' : 230,
          'weight_kg' : 104.6,
          'position' : 'SF',
          'uniform_number' : 25
        }, {
          'last_name' : 'Siva',
          'first_name' : 'Peyton',
          'display_name' : 'Peyton Siva',
          'birthdate' : '1990-10-24',
          'age' : 22,
          'birthplace' : 'Seattle, Washington, USA',
          'height_in' : 72,
          'height_cm' : 182.9,
          'height_m' : 1.8,
          'height_formatted' : '6\'0\'',
          'weight_lb' : 185,
          'weight_kg' : 84.1,
          'position' : 'PG',
          'uniform_number' : 34
        }, {
          'last_name' : 'Smith',
          'first_name' : 'Josh',
          'display_name' : 'Josh Smith',
          'birthdate' : '1985-12-05',
          'age' : 27,
          'birthplace' : 'College Park, Georgia, USA',
          'height_in' : 81,
          'height_cm' : 205.7,
          'height_m' : 2.1,
          'height_formatted' : '6\'9\'',
          'weight_lb' : 225,
          'weight_kg' : 102.3,
          'position' : 'PF',
          'uniform_number' : 6
        }, {
          'last_name' : 'Stuckey',
          'first_name' : 'Rodney',
          'display_name' : 'Rodney Stuckey',
          'birthdate' : '1986-04-21',
          'age' : 27,
          'birthplace' : 'Seattle, Washington, USA',
          'height_in' : 77,
          'height_cm' : 195.6,
          'height_m' : 2.0,
          'height_formatted' : '6\'5\'',
          'weight_lb' : 205,
          'weight_kg' : 93.2,
          'position' : 'SG',
          'uniform_number' : 3
        }, {
          'last_name' : 'Villanueva',
          'first_name' : 'Charlie',
          'display_name' : 'Charlie Villanueva',
          'birthdate' : '1984-08-24',
          'age' : 29,
          'birthplace' : 'Queens, New York, USA',
          'height_in' : 83,
          'height_cm' : 210.8,
          'height_m' : 2.1,
          'height_formatted' : '6\'11\'',
          'weight_lb' : 240,
          'weight_kg' : 109.1,
          'position' : 'PF',
          'uniform_number' : 31
        } ]
      }
    };
  }
});
